//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week8HurdleWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string isbnId { get; set; }
        public string authorId { get; set; }
        public string autFName { get; set; }
        public string autLName { get; set; }
        public string autTFNum { get; set; }
        public string Title { get; set; }
        public string yearPublished { get; set; }
        public string studentId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Student Student { get; set; }
    }
}
